export const playerImages = [
 require('../assets/people/Person1.png'),
 require('../assets/people/Person2.png'),
 require('../assets/people/Person3.png'),
 require('../assets/people/Person4.png'),
 require('../assets/people/Person5.png'),
 require('../assets/people/Person6.png'),
 require('../assets/people/Person7.png'),
 require('../assets/people/Person8.png'),
 require('../assets/people/Person9.png'),
 require('../assets/people/Person10.png'),
 require('../assets/people/Person11.png'),
 require('../assets/people/Person12.png'),
 require('../assets/people/Person13.png'),
 require('../assets/people/Person14.png'),
 require('../assets/people/Person15.png'),
 require('../assets/people/Person16.png'),
 require('../assets/people/Person17.png'),
 require('../assets/people/Person18.png'),
 require('../assets/people/Person19.png'),
 require('../assets/people/Person20.png'),
 require('../assets/people/Person21.png'),
 require('../assets/people/Person22.png'),
 require('../assets/people/Person23.png'),
 require('../assets/people/Person24.png'),
 require('../assets/people/Person25.png'),
 require('../assets/people/Person26.png')
]

export const playerPhrases = [
 'I think this is a high one',
 'I think this is a low one',
 'This one is red, I can feel it',
 'This one is blue, I can feel it',
 'I had the £250,000 last time',
 'I had the 1p last time',
 'This is the 10p, I can feel it.',
 'Good Luck',
 'Good Luck',
 'I hope this is low',
 "I've got a bad feeling",
 'I really want you to do well',
 'I think this is a big one',
 'We are all rooting for you',
 'You are only here once',
 "I'm sure this one is a blue",
 "You just need to believe",
 "You can do it",
 "Best of luck",
 "Hope this is low",
 "All the best"
]
